"""Phase 6 Stage 5b (ADR 0009): morning triage email.

Reads the latest assertion_run results and emails a triage summary to
the operator. Format leads with overall PASS/FAIL count, then groups
failures by category with sample failures inline.

Intended schedule: 08:00 ET via new rexfinhub-morning-summary.timer
(Phase 6 Stage 6 — replaces the 20:15 ET pipeline_summary.py).

Usage:
    python scripts/morning_triage_email.py                # send live
    python scripts/morning_triage_email.py --dry-run      # print to stdout
    python scripts/morning_triage_email.py --to <addr>    # override recipient
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
# Run as `python scripts/morning_triage_email.py` puts scripts/ on sys.path,
# not the repo root — so `import webapp.*` fails. Add the repo root explicitly.
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
DEFAULT_DB = PROJECT_ROOT / "data" / "etp_tracker.db"
DEFAULT_RECIPIENT = "relasmar@rexfin.com"


def latest_run(conn: sqlite3.Connection) -> list[dict]:
    """Return the most recent assertion run's results."""
    latest_row = conn.execute(
        "SELECT MAX(run_at) FROM assertion_run"
    ).fetchone()
    if not latest_row or not latest_row[0]:
        return []
    rows = conn.execute("""
        SELECT assertion_name, category, passed, fail_count, sample_json, details
        FROM assertion_run
        WHERE run_at = ?
        ORDER BY category, assertion_name
    """, (latest_row[0],)).fetchall()
    out = []
    for r in rows:
        try:
            sample = json.loads(r[4]) if r[4] else []
        except json.JSONDecodeError:
            sample = []
        out.append({
            "name": r[0], "category": r[1],
            "passed": bool(r[2]), "fail_count": r[3],
            "sample": sample, "detail": r[5] or "",
        })
    return out


def render_html(results: list[dict], run_at: str) -> str:
    passed = sum(1 for r in results if r["passed"])
    failed = len(results) - passed
    overall_color = "#059669" if failed == 0 else ("#d97706" if failed <= 2 else "#dc2626")
    overall_label = "ALL CLEAR" if failed == 0 else (f"{failed} ITEMS" if failed <= 2 else f"{failed} ITEMS — ATTENTION")

    body = []
    body.append('<table style="font-family:system-ui,Arial,sans-serif;width:100%;max-width:700px;border-collapse:collapse;background:#fff;border:1px solid #e2e8f0;">')
    body.append('<tr><td style="padding:20px 24px;border-bottom:2px solid #e2e8f0;">')
    body.append(f'<div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.06em;">REX FinHub | Daily Triage</div>')
    body.append(f'<div style="font-size:22px;font-weight:700;color:#0f172a;margin-top:4px;">{run_at[:19]}</div>')
    body.append(f'<div style="display:inline-block;margin-top:8px;padding:4px 12px;background:{overall_color};color:#fff;font-size:12px;font-weight:700;border-radius:4px;">{overall_label}</div>')
    body.append(f' <span style="font-size:13px;color:#64748b;margin-left:8px;">{passed} / {len(results)} assertions passed</span>')
    body.append('</td></tr>')

    # Group by category
    by_cat: dict[str, list[dict]] = {}
    for r in results:
        by_cat.setdefault(r["category"], []).append(r)

    for category, items in by_cat.items():
        cat_failed = sum(1 for r in items if not r["passed"])
        cat_color = "#059669" if cat_failed == 0 else "#d97706"
        body.append(f'<tr><td style="padding:16px 24px 4px;border-top:1px solid #f1f5f9;">')
        body.append(f'<div style="font-size:11px;font-weight:700;color:{cat_color};text-transform:uppercase;letter-spacing:.06em;">{category}</div>')
        body.append('</td></tr>')
        for r in items:
            mark = "&#10003;" if r["passed"] else "&#10007;"
            row_color = "#0f172a" if r["passed"] else "#991b1b"
            body.append(f'<tr><td style="padding:6px 24px 6px 36px;font-size:13px;color:{row_color};">')
            body.append(f'<span style="display:inline-block;width:14px;color:{cat_color};">{mark}</span>')
            body.append(f' <span style="font-weight:600;">{r["name"]}</span>')
            body.append(f' <span style="color:#64748b;">— {r["detail"]}</span>')
            if not r["passed"] and r["sample"]:
                body.append('<ul style="margin:6px 0 0 28px;padding:0;font-size:12px;color:#475569;">')
                for s in r["sample"][:5]:
                    parts = ", ".join(f"{k}={v}" for k, v in s.items())
                    body.append(f'<li>{parts}</li>')
                body.append('</ul>')
            body.append('</td></tr>')

    body.append('<tr><td style="padding:16px 24px;background:#f8fafc;border-top:1px solid #e2e8f0;font-size:11px;color:#64748b;">')
    body.append('Generated by <code>scripts/run_assertions.py</code> + <code>scripts/morning_triage_email.py</code>. ')
    body.append('Per ADR 0009 Phase 6 Stage 5.')
    body.append('</td></tr>')
    body.append('</table>')
    return "".join(body)


def render_text(results: list[dict], run_at: str) -> str:
    passed = sum(1 for r in results if r["passed"])
    failed = len(results) - passed
    lines = [
        f"REX FinHub Daily Triage  {run_at[:19]}",
        f"  {passed} / {len(results)} passed   ({failed} attention items)",
        "",
    ]
    by_cat: dict[str, list[dict]] = {}
    for r in results:
        by_cat.setdefault(r["category"], []).append(r)
    for category, items in by_cat.items():
        lines.append(f"[{category.upper()}]")
        for r in items:
            mark = "PASS" if r["passed"] else "FAIL"
            lines.append(f"  [{mark}] {r['name']:30s} {r['detail']}")
            if not r["passed"] and r["sample"]:
                for s in r["sample"][:3]:
                    parts = ", ".join(f"{k}={v}" for k, v in s.items())
                    lines.append(f"        -> {parts}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=str(DEFAULT_DB))
    ap.add_argument("--dry-run", action="store_true",
                    help="Print to stdout instead of sending email")
    ap.add_argument("--to", default=DEFAULT_RECIPIENT,
                    help=f"Override recipient (default: {DEFAULT_RECIPIENT})")
    args = ap.parse_args()

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"ERROR: DB not found at {db_path}", file=sys.stderr)
        return 1

    conn = sqlite3.connect(str(db_path))
    try:
        results = latest_run(conn)
        if not results:
            print("No assertion_run rows found. Run scripts/run_assertions.py first.",
                  file=sys.stderr)
            return 1
        run_at = max(r["detail"] for r in results) if False else ""
        run_at = conn.execute("SELECT MAX(run_at) FROM assertion_run").fetchone()[0]

        failed_n = sum(1 for r in results if not r["passed"])
        subject = f"[REX TRIAGE] {datetime.utcnow().strftime('%Y-%m-%d')} — "
        subject += "ALL CLEAR" if failed_n == 0 else f"{failed_n} items need attention"

        text = render_text(results, run_at)

        if args.dry_run:
            print("=" * 60)
            print(f"Subject: {subject}")
            print(f"To: {args.to}")
            print("=" * 60)
            print(text)
            print("=" * 60)
            print("DRY-RUN — not sent")
            return 0

        # Live send via Graph API (same pathway as the existing pipeline summary)
        html = render_html(results, run_at)
        try:
            from webapp.services.graph_email import send_via_graph
        except ImportError:
            print(f"ERROR: graph_email not importable; install webapp deps", file=sys.stderr)
            return 1
        ok = send_via_graph(
            recipients=[args.to],
            subject=subject,
            html_body=html,
            text_body=text,
        )
        print("sent" if ok else "send FAILED")
        return 0 if ok else 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
